### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by CreaterLL** [qkrdmsghk/TextSSL#2]
您好，数据会上传吗，我在项目中似乎没有找到。

**Comment by qkrdmsghk** [comment]
Hi, I have uploaded the corresponding contents on how to reprocess the R8 and R52 datasets with punctuations, the remaining three datasets are used based on the original dataset with punctuations provided by textgcn, thanks.

**Comment by qkrdmsghk** [comment]
> 您好，数据会上传吗，我在项目中似乎没有找到。

Hi, I have uploaded the corresponding contents on how to reprocess the R8 and R52 datasets with punctuations, the remaining three datasets are used based on the original dataset with punctuations provided by textgcn, thanks.
