### ISSUE TITLE
Dataset download link not working

### ISSUE THREAD

**Issue by LaviRoars** [qkrdmsghk/TextSSL#6]
Hi, 

Thank you for sharing the code for re-extracting the dataset. I'm following the instructions provided in the image below but the link to the dataset does not work. Can you please share the updated link? Thank you!

<img width="872" alt="image" src="https://github.com/user-attachments/assets/b57b9936-18c7-4e51-8393-80f40715a4c5">

**Comment by qkrdmsghk** [comment]
Thank you for pointing out the issues.

It seems that the dataset link is currently not working. I noticed that Hugging Face also provides the source data for the Reuters-21578 dataset. I use the ModApte split among the available splitting methods.

You are welcome to use the source from Hugging Face. 

Alternatively, I’ve also uploaded my source data just now (https://github.com/qkrdmsghk/TextSSL/blob/master/Reuters21578-Apte-115Cat.zip). 
Feel free to use whichever is more convenient.

Best,
Yinhua

**Comment by LaviRoars** [comment]
It worked! thank you!
